# Generated by Django 3.1 on 2020-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usersignup_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('videolink', models.CharField(max_length=500)),
                ('pdfdrivelink', models.CharField(max_length=1000)),
            ],
        ),
    ]
